### ISSUE TITLE
./MaiARK: 2: Syntax error: newline unexpected 

### ISSUE THREAD

**Issue by hd8023** [shidahuilang/QL-#14]
./MaiARK: 2: Syntax error: newline unexpected 

一直报错这个，请问有什么解决方法阿

**Comment by kk-dark** [comment]
我用的docker版，也是报这个错误，然后配置完了还进不去web页面。这个报错貌似是某个字典{}最后一行少一个逗号。

**Comment by shidahuilang** [comment]
应该是编码问题，win和linux换行符也不一样，等我修复一下

**Comment by tabs** [comment]
> 应该是编码问题，win和linux换行符也不一样，等我修复一下

啥时候修复好啊，maiark现在启动不了

 正常连接到ddo的服务器
 cpu 架构为 x86_64 即 amd64
 拷贝 MaiARK 成功
 MaiARK 存在
 MaiARK 删除成功
 拷贝 MaiARK 成功
 MaiARK更新完毕！
 版本号为：<?xml
 arkconfig.json 存在
 arktemplates1129 存在
./MaiARK: 2: Syntax error: newline unexpected

**Comment by tabs** [comment]
> > 应该是编码问题，win和linux换行符也不一样，等我修复一下
> 
> 啥时候修复好啊，maiark现在启动不了
> 
> 正常连接到ddo的服务器 cpu 架构为 x86_64 即 amd64 拷贝 MaiARK 成功 MaiARK 存在 MaiARK 删除成功 拷贝 MaiARK 成功 MaiARK更新完毕！ 版本号为：<?xml arkconfig.json 存在 arktemplates1129 存在 ./MaiARK: 2: Syntax error: newline unexpected

用的是docker

**Comment by luciferkids** [comment]
![image](https://github.com/shidahuilang/QL-/assets/32830168/76019c41-e62e-4bee-80bf-a04edd173335)
如图报错。。。

**Comment by luciferkids** [comment]
> 应该是编码问题，win和linux换行符也不一样，等我修复一下

还有救么？

**Comment by lc0w0cl** [comment]
我也一样，部署不了

**Comment by jasperchen912** [comment]
<Message>Due to your account is arrears, it is unavailable until you recharge.</Message>

**Comment by shidahuilang** [comment]
![image](https://github.com/shidahuilang/QL-/assets/81285256/5b2646f9-a449-4101-ab8d-520b3d91daf4)
测试了 没有遇到你说的问题

**Comment by kk-dark** [comment]
> ![image](https://user-images.githubusercontent.com/81285256/276890768-5b2646f9-a449-4101-ab8d-520b3d91daf4.png) 测试了 没有遇到你说的问题

这个问题我刚也去试了下，又没有了，但是出现新的问题了，短信登录功能无法使用
![image](https://github.com/shidahuilang/QL-/assets/61961949/3d0d6bcf-4cd4-4deb-acbe-c610ec2576ce)

**Comment by luciferkids** [comment]
> ![image](https://user-images.githubusercontent.com/81285256/276890768-5b2646f9-a449-4101-ab8d-520b3d91daf4.png) 测试了 没有遇到你说的问题

原版的报错提示额度用完。

**Comment by luciferkids** [comment]
原版的进入容器后错误查看MaiARK文件发现如下错误。

root@m1:/MaiARK# cat MaiARK 
<?xml version='1.0' encoding='utf-8' ?>
<Error>
        <Code>UnavailableForLegalReasons</Code>
        <Message>Due to your account is arrears, it is unavailable until you recharge.</Message>
        <Resource>/MaiARK_Linux_amd64</Resource>
        <RequestId>NjUzMjRlN2NfOGNlZjk4MWVfMTMxMGJfNGFiZWU3NA==</RequestId>
        <TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTVlNGMxNDIzNDk3MzBjZDllZGY1MzE5MTM5N2ZmOTE4YWYyNDY1NTJkYWIwODlhOWM5Zjk5NjM2ODdhZTI1MWQ=</TraceId>
</Error>

**Comment by luciferkids** [comment]
用你版本的容器报以下错误，第一天拉取你容器的时候都是正常的。第三天开始好像就失效了。

 * Running on http://172.17.0.3:8082/ (Press CTRL+C to quit)
192.168.18.134 - - [20/Oct/2023 17:58:30] "GET / HTTP/1.1" 200 -
192.168.18.134 - - [20/Oct/2023 17:58:30] "GET /static/js/main.7c9d5a0f.js HTTP/1.1" 200 -
192.168.18.134 - - [20/Oct/2023 17:58:30] "GET /static/css/main.620500bd.css HTTP/1.1" 200 -
192.168.18.134 - - [20/Oct/2023 17:58:30] "GET /static/pic/background.jpg HTTP/1.1" 200 -
192.168.18.134 - - [20/Oct/2023 17:58:31] "GET /static/pic/favicon.png HTTP/1.1" 200 -
[2023-10-20 17:58:41,421] ERROR in app: Exception on /getsms [GET]
Traceback (most recent call last):
  File "flask/app.py", line 2073, in wsgi_app
  File "flask/app.py", line 1518, in full_dispatch_request
  File "flask/app.py", line 1516, in full_dispatch_request
  File "flask/app.py", line 1502, in dispatch_request
  File "MaiARK_Linux_amd64.py", line 71, in getsms
  File "lib.pyx", line 377, in lib.getsms
  File "lib.pyx", line 297, in lib.getvt
KeyError: 'b2'
192.168.18.134 - - [20/Oct/2023 17:58:41] "GET /getsms?mobile=*********** HTTP/1.1" 500 -

**Comment by David-One** [comment]
> 原版的进入容器后错误查看MaiARK文件发现如下错误。
> 
> root@m1:/MaiARK# cat MaiARK
> 
> `UnavailableForLegalReasons` Due to your account is arrears, it is unavailable until you recharge. /MaiARK_Linux_amd64 NjUzMjRlN2NfOGNlZjk4MWVfMTMxMGJfNGFiZWU3NA== OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTVlNGMxNDIzNDk3MzBjZDllZGY1MzE5MTM5N2ZmOTE4YWYyNDY1NTJkYWIwODlhOWM5Zjk5NjM2ODdhZTI1MWQ=

我也是一样的错误

**Comment by zkn999** [comment]
./MaiARK: 2: Syntax error: newline unexpected
 正常连接到ddo的服务器
 cpu 架构为 x86_64 即 amd64
 拷贝 MaiARK 成功
 MaiARK 存在
 MaiARK 删除成功
 拷贝 MaiARK 成功
 MaiARK更新完毕！
 版本号为：<?xml
 arkconfig.json 存在
 arktemplates1129 存在

运行不了了，还有救吗？

**Comment by dongyubin** [comment]
> ./MaiARK: 2: Syntax error: newline unexpected
> 
> 一直报错这个，请问有什么解决方法阿

改用了Rabbit了，[搭建教程](https://www.wangdu.site/course/1848.html)

**Comment by hd8023** [comment]
> ![image](https://user-images.githubusercontent.com/81285256/276890768-5b2646f9-a449-4101-ab8d-520b3d91daf4.png) 测试了 没有遇到你说的问


有没有可能是docker版的才报错

**Comment by hd8023** [comment]
> ![image](https://user-images.githubusercontent.com/81285256/276890768-5b2646f9-a449-4101-ab8d-520b3d91daf4.png) 测试了 没有遇到你说的问题

重试了好多遍，一直报这个错误， 一键安装脚本也没有用，docker命令安装之后就一直报这个错误

**Comment by hd8023** [comment]
> 应该是编码问题，win和linux换行符也不一样，等我修复一下
 
能否加个v，协助一下下
